name: rnn-pos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - absl-py=1.0.0
  - addict=2.4.0
  - aiohttp=3.7.4.post0
  - antlr-python-runtime=4.8
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.4.0
  - bitarray=2.4.1
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cachetools=4.2.4
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=35.0.0
  - future=0.18.2
  - gast=0.3.3
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - hdf5=1.10.6
  - hydra-core=1.1.1
  - icu=68.2
  - idna=3.3
  - importlib_resources=5.7.1
  - joblib=1.1.0
  - jpeg=9e
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - libcurl=7.79.1
  - libcxx=12.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libssh2=1.10.0
  - llvm-openmp=12.0.0
  - markdown=3.2.1
  - multidict=5.2.0
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - numexpr=2.8.1
  - numpy-base=1.22.3
  - oauthlib=3.2.0
  - omegaconf=2.1.1
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.2
  - pip=21.2.4
  - portalocker=1.4.0
  - protobuf=3.15.8
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.8
  - pytorch=1.10.2
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2021.08.01
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - sacrebleu=2.1.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.38.3
  - tabulate=0.8.9
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.5
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tqdm=4.64.0
  - typing=3.10.0.0
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - werkzeug=2.1.2
  - wheel=0.37.1
  - wrapt=1.13.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.0
  - zipp=3.8.0
  - zlib=1.2.12
  - pip:
    - annoy==1.17.0
    - fasteners==0.17.3
    - h5py==3.7.0
    - lz4==4.0.1
    - numpy==1.22.4
    - pymagnitude==0.1.143
    - torch==1.11.0
    - typing-extensions==4.2.0
    - xxhash==3.0.0
