name: rnn-pos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - addict=2.4.0
  - certifi=2021.10.8
  - click=8.0.4
  - colorama=0.4.4
  - keras=2.4.3
  - nltk=3.7
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.2
  - pip=21.2.4
  - pycparser=2.21
  - pyparsing=3.0.4
  - python=3.8.13
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - tk=8.6.11
  - tqdm=4.64.0
  - wheel=0.37.1
